"""
Django settings for uni_core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-43k2#d%2$)*%s)*+%w0v5apipj@ezs=pbg9(tp69)9qs_*sic9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom apps
    'accounts',
    'tickets',
    'notifications',  # نظام الإشعارات الداخلية
    
    # Third party
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Custom middleware - يجب أن يكون بعد AuthenticationMiddleware
    'accounts.middleware.LoginTrackingMiddleware',  # تتبع دخول المستخدمين
    'tickets.middleware.ForceAcknowledgmentMiddleware',
]

ROOT_URLCONF = 'uni_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.global_mails',
            ],
        },
    },
]

WSGI_APPLICATION = 'uni_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Baghdad'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration (for notifications)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Change to SMTP in production
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  # Set in production
EMAIL_HOST_PASSWORD = ''  # Set in production
DEFAULT_FROM_EMAIL = 'noreply@university.edu'  # Default sender email

# SLA Deadlines (in hours) - المهل الزمنية بالساعات
# حرج = يوم واحد، عاجل = يومين، عادي = 3 أيام
SLA_DEADLINES = {
    'normal': 72,      # 3 أيام (72 ساعة) للأولوية العادية
    'urgent': 48,      # يومين (48 ساعة) للأولوية العاجلة
    'critical': 24,    # يوم واحد (24 ساعة) للأولوية الحرجة
}

# Escalation Settings
ESCALATION_LEVELS = ['employee', 'head', 'dean', 'president']
AUTO_REASSIGN_AFTER_HOURS = 48  # Auto-reassign ticket after 48 hours

# Celery Beat Schedule - نظام صارم للمتابعة
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # فحص انتهاكات SLA كل 5 دقائق
    'check-sla-violations': {
        'task': 'tickets.tasks.check_sla_violations',
        'schedule': crontab(minute='*/5'),
    },
    # إرسال تحذيرات المهلة كل 15 دقيقة
    'send-deadline-warnings': {
        'task': 'tickets.tasks.send_deadline_warnings',
        'schedule': crontab(minute='*/15'),
    },
    # حساب النقاط الجزائية يومياً في منتصف الليل
    'calculate-daily-penalties': {
        'task': 'tickets.tasks.calculate_daily_penalties',
        'schedule': crontab(hour=23, minute=59),
    },
    # إعادة تعيين الطلبات المتأخرة كل ساعة
    'auto-reassign-tickets': {
        'task': 'tickets.tasks.auto_reassign_tickets',
        'schedule': crontab(minute=0),
    },
    # إرسال التقرير اليومي في الساعة 8 صباحاً
    'send-daily-report': {
        'task': 'tickets.tasks.send_daily_report',
        'schedule': crontab(hour=8, minute=0),
    },
    # حساب مقاييس الأداء كل 6 ساعات
    'generate-performance-metrics': {
        'task': 'tickets.tasks.generate_performance_metrics',
        'schedule': crontab(minute=0, hour='*/6'),
    },
}

# Auth Settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ============================================
# PERFORMANCE OPTIMIZATION
# ============================================

# Caching Configuration
# ملاحظة: استخدام LocMemCache بدلاً من Redis للتطوير
# لتفعيل Redis: شغّل redis-server ثم غيّر BACKEND إلى RedisCache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',  # استخدام الذاكرة بدلاً من Redis
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
    }
}

# لتفعيل Redis لاحقاً (بعد تشغيل redis-server):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'TIMEOUT': 300,
#         'KEY_PREFIX': 'uni_tickets',
#     }
# }

# Session Configuration (use Redis for sessions too)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# ============================================
# LOGGING CONFIGURATION
# ============================================

import os
LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_tickets': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'tickets.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_celery': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'celery.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        'tickets': {
            'handlers': ['console', 'file_tickets'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'file_celery'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================
# SECURITY ENHANCEMENTS
# ============================================

# Security Headers (for production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CSRF Protection
CSRF_COOKIE_HTTPONLY = True

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Allowed file extensions for uploads
ALLOWED_UPLOAD_EXTENSIONS = ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt']

