# Generated by Django 4.2.7 on 2025-12-16 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "عادي"),
                            ("urgent", "عاجل"),
                            ("critical", "حرج"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("pending_ack", "بانتظار التأكيد"),
                            ("in_progress", "قيد المعالجة"),
                            ("resolved", "تم الحل"),
                            ("closed", "مغلق"),
                            ("returned", "معاد/مرفوض"),
                            ("violated", "مخالف (تجاوز المهلة)"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "escalation_level",
                    models.CharField(
                        choices=[
                            ("none", "لا يوجد"),
                            ("head", "رئيس القسم"),
                            ("dean", "العميد"),
                            ("president", "رئيس الجامعة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="مستوى التصعيد",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التأكيد"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الحل"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإغلاق"
                    ),
                ),
                (
                    "sla_deadline",
                    models.DateTimeField(verbose_name="الموعد النهائي (SLA)"),
                ),
                (
                    "target_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="التاريخ المستهدف (اختياري)"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ticket_attachments/",
                        verbose_name="مرفق مع الطلب",
                    ),
                ),
                (
                    "close_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإغلاق"),
                ),
                (
                    "close_attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ticket_closures/",
                        verbose_name="مرفقات الإغلاق",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعين له",
                    ),
                ),
                (
                    "assigned_to_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعينون لهم",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المنشئ",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="accounts.department",
                        verbose_name="القسم المعني",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_tickets",
                        to="accounts.department",
                        verbose_name="الأقسام المعنية",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "تم الإنشاء"),
                            ("assigned", "تم التعيين"),
                            ("acknowledged", "تم التأكيد"),
                            ("escalated", "تم التصعيد"),
                            ("reassigned", "تم إعادة التعيين"),
                            ("resolved", "تم الحل"),
                            ("closed", "تم الإغلاق"),
                            ("returned", "تم إرجاع/رفض الطلب"),
                            ("commented", "تم التعليق"),
                            ("violation", "تم تسجيل مخالفة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإجراء",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="الملاحظات")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="action_attachments/",
                        verbose_name="مرفق",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="tickets.ticket",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إجراء",
                "verbose_name_plural": "الإجراءات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإقرار"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="tickets.ticket",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إقرار استلام",
                "verbose_name_plural": "إقرارات الاستلام",
                "ordering": ["-acknowledged_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket", "user"], name="tickets_tic_ticket__d166e2_idx"
                    ),
                    models.Index(
                        fields=["user", "-acknowledged_at"],
                        name="tickets_tic_user_id_b92d33_idx",
                    ),
                ],
                "unique_together": {("ticket", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="ticket_status_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["priority"], name="ticket_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["created_at"], name="ticket_created_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["sla_deadline"], name="ticket_sla_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "priority"], name="ticket_status_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "sla_deadline"], name="ticket_status_sla_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["department", "status"], name="ticket_dept_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_to", "status"], name="ticket_assign_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_at", "department"], name="ticket_created_dept_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority", "escalation_level"], name="ticket_priority_esc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["created_by", "created_at"], name="ticket_creator_time_idx"
            ),
        ),
    ]
