# Generated by Django 5.1 on 2025-11-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('critical', 'حرج')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('pending_ack', 'بانتظار التأكيد'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق'), ('violated', 'مخالف (تجاوز المهلة)')], default='new', max_length=20, verbose_name='الحالة')),
                ('escalation_level', models.CharField(choices=[('none', 'لا يوجد'), ('head', 'رئيس القسم'), ('dean', 'العميد'), ('president', 'رئيس الجامعة')], default='none', max_length=20, verbose_name='مستوى التصعيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('sla_deadline', models.DateTimeField(verbose_name='الموعد النهائي (SLA)')),
                ('close_notes', models.TextField(blank=True, verbose_name='ملاحظات الإغلاق')),
                ('close_attachments', models.FileField(blank=True, null=True, upload_to='ticket_closures/', verbose_name='مرفقات الإغلاق')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='المعين له')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.department', verbose_name='القسم المعني')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'تم الإنشاء'), ('assigned', 'تم التعيين'), ('acknowledged', 'تم التأكيد'), ('escalated', 'تم التصعيد'), ('reassigned', 'تم إعادة التعيين'), ('resolved', 'تم الحل'), ('closed', 'تم الإغلاق'), ('commented', 'تم التعليق')], max_length=20, verbose_name='نوع الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tickets.ticket', verbose_name='الطلب')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إجراء',
                'verbose_name_plural': 'الإجراءات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'sla_deadline'], name='tickets_tic_status_5fff59_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status'], name='tickets_tic_departm_af9754_idx'),
        ),
    ]
