# Generated by Django 5.1 on 2025-11-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_tickets_tic_assigne_e36302_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/', verbose_name='مرفق مع الطلب'),
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='action_attachments/', verbose_name='مرفق'),
        ),
    ]
