# Generated by Django 5.1 on 2025-11-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0003_ticket_attachment_ticketaction_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='multi_tickets', to='accounts.department', verbose_name='الأقسام المعنية'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.department', verbose_name='القسم المعني'),
        ),
    ]
