# Generated by Django 5.1 on 2025-11-23 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_departments_alter_ticket_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_to_users',
            field=models.ManyToManyField(blank=True, related_name='multi_assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='المعينون لهم'),
        ),
    ]
