# Generated by Django 4.2.7 on 2025-12-16 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان البريد"),
                ),
                ("message", models.TextField(verbose_name="محتوى البريد")),
                (
                    "mail_type",
                    models.CharField(
                        choices=[
                            ("announcement", "منشور"),
                            ("alert", "تنبيه"),
                            ("event", "فعالية"),
                            ("info", "معلومة"),
                            ("other", "أخرى"),
                        ],
                        default="announcement",
                        max_length=20,
                        verbose_name="نوع البريد",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(blank=True, null=True, verbose_name="رابط خارجي"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "بريد عام",
                "verbose_name_plural": "البريد العام",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GlobalMailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="global_mail_attachments/",
                        verbose_name="مرفق (صورة أو PDF أو فيديو)",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notifications.globalmail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_ticket", "طلب جديد"),
                            ("ticket_assigned", "تم التعيين"),
                            ("ticket_acknowledged", "تم التأكيد"),
                            ("ticket_escalated", "تم التصعيد"),
                            ("deadline_approaching", "اقتراب الموعد"),
                            ("ticket_commented", "تعليق جديد"),
                            ("ticket_closed", "تم الإغلاق"),
                            ("ticket_violated", "تجاوز المهلة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticket",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
